priority_planner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('priority_planners.urls')),
]

priority_planners/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path

from . import views


app_name = 'priority_planners'
urlpatterns= [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all goals.
    path('goals/', views.goals, name='goals'),
    # Page that details a goal
    path('goals/<int:goal_id>/', views.goal, name='goal'),
    # Page that details an update
    path('updates/<int:update_id>/', views.update, name='update'),
    # Page for adding a new goal
    path('new_goal/', views.new_goal, name='new_goal'),
    # Page for adding a new update
    path('new_update/<int:goal_id>/', views.new_update, name='new_update'),
    # Page for editing an goal
    path('edit_goal/<int:goal_id>/', views.edit_goal, name='edit_goal'),
    # Path for editing an update
    path('edit_update/<int:update_id>/', views.edit_update, name='edit_update'),
    # Path for deleting a goal
    path('delete_goal/<int:goal_id>/', views.delete_goal, name='delete_goal'),
    # Path for deleting an update
    path('delete_update/<int:update_id>/', views.delete_update, name='delete_update'),
    # Path for finishing a goal
    path('finish_goal/<int:goal_id>/', views.finish_goal, name='finish_goal'),

]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

priority_planners/models.py
from django.db import models
from django.contrib.auth.models import User
from colorful.fields import RGBColorField


class Goal(models.Model):
    """A Goal the user wants to complete."""
    parent = None
    color = RGBColorField()
    title = models.CharField(max_length=200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    date_completed = models.DateTimeField(null=True)
    completed = models.BooleanField(default=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model"""
        return self.title


class Update(models.Model):
    """A note regarding a specific goal."""
    parent = models.ForeignKey(Goal, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model"""
        return self.title

priority_planners/forms.py
from django import forms

from .models import Goal, Update


class GoalForm(forms.ModelForm):
    class Meta:
        model = Goal
        fields = ['title', 'text']
        labels = {'title': '', 'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}


class UpdateForm(forms.ModelForm):
    class Meta:
        model = Update
        fields = ['title', 'text']
        labels = {'title': '', 'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

priority_planners/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.http import Http404

from .models import Goal, Update
from .forms import GoalForm, UpdateForm


def index(request):
    """The home page for Priority Planner."""
    return render(request, 'priority_planners/index.html')


@login_required
def goals(request):
    """Show all goals with their updates."""
    goals_all = Goal.objects.filter(owner=request.user).order_by('date_added')
    goal_list = [goal for goal in goals_all if goal.completed is False]
    finished = [goal for goal in goals_all if goal.completed is True]

    goal_updates = [goal.update_set.order_by('-date_added')
                    for goal in goal_list]
    finished_updates = [goal.update_set.order_by('-date_added')
                        for goal in finished]

    # Lists of tuples containing goals and a list of their updates
    goals_and_updates = [(goal, updates) for goal, updates
                         in zip(goal_list, goal_updates)]
    finished_and_updates = [(goal, updates) for goal, updates
                            in zip(finished, finished_updates)]

    context = {'goals': goals_and_updates, 'finished': finished_and_updates}
    return render(request, 'priority_planners/goals.html', context)


@login_required
def goal(request, goal_id):
    """Show a single goal and it's updates"""
    goal = get_object_or_404(Goal, id=goal_id)
    # Make sure the goal belongs to the current user.
    if goal.owner != request.user:
        raise Http404

    updates = goal.update_set.order_by('-date_added')
    context = {'goal': goal, 'updates': updates}
    return render(request, 'priority_planners/goal.html', context)


@login_required
def update(request, update_id):
    """Show a single update and it's text"""
    update = get_object_or_404(Update, id=update_id)
    if update.parent.owner != request.user:
        raise Http404
    context = {'update': update}
    return render(request, 'priority_planners/update.html', context)


@login_required
def new_goal(request):
    """Add a new goal."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = GoalForm()
    else:
        # POST data submitted; process data.
        form = GoalForm(data=request.POST)
        if form.is_valid():
            new_goal = form.save(commit=False)
            new_goal.owner = request.user
            new_goal.save()
            return redirect('priority_planners:goals')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'priority_planners/new_goal.html', context)


@login_required
def new_update(request, goal_id):
    """ Add a new update for a particular goal"""
    goal = get_object_or_404(Goal, id=goal_id)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = UpdateForm()
    else:
        # POST data submitted; process data.
        form = UpdateForm(data=request.POST)
        if form.is_valid():
            new_update = form.save(commit=False)
            new_update.parent = goal
            if goal.owner != request.user:
                raise Http404
            new_update.save()
            return redirect('priority_planners:goal', goal_id=goal_id)

    # Display a blank or invalid form
    context = {'goal': goal, 'form': form}
    return render(request, 'priority_planners/new_update.html', context)


@login_required
def edit_goal(request, goal_id):
    """Edit an existing goal"""
    goal = get_object_or_404(Goal, id=goal_id)

    if request.method != 'POST':
        # Initial request; pre-fill form with the current goal.
        form = GoalForm(instance=goal)
    else:
        # Post data submitted; process data.
        form = GoalForm(instance=goal, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('priority_planners:goal', goal_id=goal.id)

    context = {'goal': goal, 'form': form}
    return render(request, 'priority_planners/edit_goal.html', context)


@login_required
def edit_update(request, update_id):
    """Edit an existing update"""
    update = get_object_or_404(Update, id=update_id)

    if request.method != 'POST':
        # Initial request; pre-fill form with the current update.
        form = UpdateForm(instance=update)
    else:
        # Post data submitted; process data.
        form = UpdateForm(instance=update, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('priority_planners:update', update_id=update.id)

    context = {'update': update, 'form': form}
    return render(request, 'priority_planners/edit_update.html', context)


@login_required
def delete_goal(request, goal_id):
    """Delete an existing goal"""
    goal = get_object_or_404(Goal, id=goal_id)
    if request.method == 'POST':
        # confirming delete
        goal.delete()
        return redirect('priority_planners:goals')
    context = {
        "goal": goal
    }
    return render(request, 'priority_planners/delete_goal.html', context)


@login_required
def delete_update(request, update_id):
    """Delete an existing update"""
    update = get_object_or_404(Update, id=update_id)
    if request.method == 'POST':
        # confirming delete
        update.delete()
        return redirect('priority_planners:goals')
    context = {
        "update": update
    }
    return render(request, 'priority_planners/delete_update.html', context)


@login_required
def finish_goal(request, goal_id):
    """Finish an existing goal"""
    goal = get_object_or_404(Goal, id=goal_id)
    if request.method == 'POST':
        # confirming finish
        goal.date_completed = timezone.now()
        goal.completed = True
        goal.save()
        return redirect('priority_planners:goals')
    context = {
        "goal": goal
    }
    return render(request, 'priority_planners/finish_goal.html', context)

priority_planners/templates/priority_planners/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
        shrink-to-fit=no">
    <title>Priority Planner</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'priority_planners:index'%}">
            Priority Planner
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'priority_planners:goals' %}">
                        Goals</a></li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text"}">Hello, {{ user.username }}.</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <main rolw="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>

</body>

</html>

priority_planners/templates/priority_planners/delete_goal.html
{% extends "priority_planners/base.html" %}

{% block page_header %}
    <h1>Are you sure you want to delete "{{ goal }}"?</h1>
{% endblock page_header %}

{% block content %}

    <form action="{% url 'priority_planners:delete_goal' goal.id %}" method='POST'>
        {% csrf_token %}

        <h4><input type='submit' value='Yes' />  <a href="{% url 'priority_planners:goal' goal.id %}">Cancel</a></h4>
    </form>

{% endblock content %}

priority_planners/templates/priority_planners/delete_update.html
{% extends "priority_planners/base.html" %}

{% block page_header %}
    <h1>Are you sure you want to delete "{{ update }}"?</h1>
{% endblock page_header %}

{% block content %}

    <form action="{% url 'priority_planners:delete_update' update.id %}" method='POST'>
        {% csrf_token %}
        <h4><input type='submit' value='Yes' />  <a href="{% url 'priority_planners:update' update.id %}">Cancel</a></h4>
    </form>

{% endblock content %}

priority_planners/templates/priority_planners/edit_goal.html
{% extends "priority_planners/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h1><a href="{% url 'priority_planners:goal' goal.id %}">{{ goal }}</a></h1>
    <h2>Edit goal:</h2>
{% endblock page_header %}

{% block content %}

    <form action="{% url 'priority_planners:edit_goal' goal.id %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Save goal</button>
        {% endbuttons %}
    </form>

{% endblock content %}

priority_planners/templates/priority_planners/edit_update.html
{% extends "priority_planners/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h1><a href="{% url 'priority_planners:update' update.id %}">{{ update }}</a></h1>
    <h2>Edit update:</h2>
{% endblock page_header %}

{% block content %}

    <form action="{% url 'priority_planners:edit_update' update.id %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Save update</button>
        {% endbuttons %}
    </form>

{% endblock content %}

priority_planners/templates/priority_planners/finish_goal.html
{% extends "priority_planners/base.html" %}

{% block page_header %}
    <h1>You're finished with: "{{ goal }}"?</h1>
{% endblock page_header %}

{% block content %}

    <form action="{% url 'priority_planners:finish_goal' goal.id %}" method='POST'>
        {% csrf_token %}
        <h4><input type='submit' value='Yes' />  <a href="{% url 'priority_planners:goal' goal.id %}">Cancel</a></h4>
    </form>

{% endblock content %}

priority_planners/templates/priority_planners/goal.html
{% extends 'priority_planners/base.html' %}

{% block page_header %}
    <h1>Goal: {{ goal }}{% if goal.date_completed is not None %} Finished:
        {{ goal.date_completed|date:'M d, Y H:i' }}}{% endif %}</h1>
    <h3>
        <a href="{% url 'priority_planners:edit_goal' goal.id %}">Edit</a>  -
        <a href="{% url 'priority_planners:finish_goal' goal.id %}">Finish</a>  -
        <a href="{% url 'priority_planners:delete_goal' goal.id %}">Delete</a>
    </h3>
    <p>{{ goal.text }}</p>
{% endblock page_header %}

{% block content %}

    <h2>Updates:</h2>
    <ul>
        {% for update in updates %}
        <li><h3>
            {{ update.date_added|date:'M d, Y' }}:
            <a href="{% url 'priority_planners:update' update.id %}">{{ update }}</a>
        </h3></li>
        {% empty %}
            <h3>There are no updates for this goal yet.</h3>
        {% endfor %}
        <h3>
        <a href="{% url 'priority_planners:new_update' goal.id %}">Add new update</a>
        </h3>
    </ul>


{% endblock content %}

priority_planners/templates/priority_planners/goals.html
{% extends "priority_planners/base.html" %}

{% block page_header %}
    <h1>Goals</h1>
{% endblock page_header %}

{% block content %}

    <h3><a href="{% url 'priority_planners:new_goal' %}">Add a new goal</a></h3>

    <ul>
        {% for goal, updates in goals %}
            <h3><a href="{% url 'priority_planners:goal' goal.id %}">{{ goal }}</a></h3>
            {% for update in updates %}
                <li><h4>{{ update.date_added|date:'M d, Y' }}:
                    <a href="{% url 'priority_planners:update' update.id %}">{{ update }}</a>
                </h4></li>
            {% endfor %}
        {% empty %}
            <li><h3>No goals have been added yet</h3></li>
        {% endfor %}
    </ul>
    <h3>Finished Goals:</h3>
    <ul>
        {% for goal, updates in finished %}
            <h3><a href="{% url 'priority_planners:goal' goal.id %}">{{ goal }}</a>
                -    Finished: {{ goal.date_completed|date:'M d, Y' }}</h3>
            {% for update in updates %}
                <li><h4>{{ update.date_added|date:'M d, Y' }}:
                    <a href="{% url 'priority_planners:update' update.id %}">{{ update }}</a>
                </h4></li>
            {% endfor %}
        {% endfor %}
    </ul>

{% endblock content %}

priority_planners/templates/priority_planners/index.html
{% extends "priority_planners/base.html" %}
{% block page_header %}
    <div class="jumbotron">
    <h1 class="display-3">Prioritize.</h1>
        <p class="lead">Priority Planner allows you to keep track of goals
                        and check them off as you get them done. You can append
                        updates to goals as well to keep track of your progress!</p>
        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
            role="button">Register &raquo;</a>
    </div>
{% endblock page_header %}

priority_planners/templates/priority_planners/new_goal.html
{% extends "priority_planners/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h1>Add a new goal:</h1>
{% endblock page_header %}

{% block content %}

    <form action="{% url 'priority_planners:new_goal' %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Add goal</button>
        {% endbuttons %}
    </form>

{% endblock content %}

priority_planners/templates/priority_planners/new_update.html
{% extends "priority_planners/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h1><a href="{% url 'priority_planners:goal' goal.id %}">{{ goal }}</a></h1>
    <h2>Add a new update:</h2>
{% endblock page_header %}

{% block content %}

    <p></p>
    <form action="{% url 'priority_planners:new_update' goal.id %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Add update</button>
        {% endbuttons %}
    </form>

{% endblock content %}

priority_planners/templates/priority_planners/update.html
{% extends 'priority_planners/base.html' %}

{% block page_header %}
    <h1>Goal: <a href="{% url 'priority_planners:goal' update.parent.id %}">{{ update.parent.text }}</a></h1>
    <h3><a href="{% url 'priority_planners:edit_update' update.id %}">Edit</a>  -
        <a href="{% url 'priority_planners:delete_update' update.id %}">Delete</a>
    </h3>
{% endblock page_header %}

{% block content %}

    <h2>{{ update.date_added|date:'M d, Y' }}:  {{ update }}</h2>
    <h5>{{ update.text }}</h5>


{% endblock content %}